
services:
- postgresql

before_script:
- psql -c 'create database travis;' -U postgres -w
- psql -c 'create database testdb;' -U postgres -w
- psql -f 'testscript.sql'

language: node_js
node_js:
  - "6"
  - "4"

